# Generated by Django 5.1.3 on 2024-11-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Causa1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('nombreusuario', models.CharField(max_length=255)),
                ('apellidousuario', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'managed': False},
        ),
    ]
