# Generated by Django 5.1.3 on 2024-11-08 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Causa1', '0002_usuario_alter_notificacion_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificacion',
            table='Notificacion',
        ),
    ]
