# Generated by Django 5.1.3 on 2024-11-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Causa1', '0002_aud_notificacion_demanda_estampado_historial_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificacion',
            table='notificacion',
        ),
    ]
