# Generated by Django 5.1.3 on 2024-11-08 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Causa1', '0003_alter_notificacion_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificacion',
            table='notificacion',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
