# Generated by Django 5.1.3 on 2024-11-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Causa1', '0004_alter_notificacion_table_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNotificacion', models.DateField()),
                ('numjui', models.CharField(max_length=50)),
                ('nomb_tribunal', models.CharField(max_length=100)),
                ('demandante', models.CharField(max_length=100)),
                ('demandado', models.CharField(max_length=100)),
                ('repre', models.CharField(max_length=100)),
                ('mandante', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=100)),
                ('encargo', models.CharField(max_length=100)),
                ('soli', models.TextField()),
                ('arancel', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
