# Generated by Django 5.1.3 on 2024-11-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('numjui', models.CharField(max_length=255)),
                ('nomb_tribunal', models.CharField(max_length=255)),
                ('demandante', models.CharField(max_length=255)),
                ('demandado', models.CharField(max_length=255)),
                ('repre', models.CharField(max_length=255)),
                ('mandante', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('encargo', models.CharField(max_length=255)),
                ('soli', models.CharField(max_length=255)),
                ('arancel', models.CharField(max_length=255)),
                ('estado_noti', models.BooleanField(default=False)),
                ('estado_causa', models.BooleanField(default=False)),
                ('actu', models.TextField()),
            ],
        ),
    ]
