# Generated by Django 5.1.3 on 2024-11-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AUD_notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNotificacion', models.DateTimeField()),
                ('numjui', models.CharField(max_length=255)),
                ('nombTribunal', models.CharField(max_length=255)),
                ('demandante', models.CharField(max_length=255)),
                ('demandado', models.CharField(max_length=255)),
                ('repre', models.CharField(max_length=255)),
                ('mandante', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('encargo', models.CharField(max_length=255)),
                ('soli', models.CharField(max_length=255)),
                ('arancel', models.IntegerField()),
                ('arancel_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estadoNoti', models.IntegerField()),
                ('estadoCausa', models.IntegerField()),
                ('actu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aud_notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numjui', models.CharField(max_length=255)),
                ('nombTribunal', models.CharField(max_length=255)),
                ('demandante', models.CharField(max_length=255)),
                ('demandado', models.CharField(max_length=255)),
                ('repre', models.CharField(max_length=255)),
                ('mandante', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('encargo', models.CharField(max_length=255)),
                ('soli', models.CharField(max_length=255)),
                ('arancel', models.IntegerField()),
                ('arancel_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('actu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'demanda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaNotificacion', models.DateTimeField(blank=True, null=True)),
                ('numjui', models.CharField(blank=True, max_length=255, null=True)),
                ('nombTribunal', models.CharField(blank=True, max_length=255, null=True)),
                ('demandante', models.CharField(blank=True, max_length=255, null=True)),
                ('demandado', models.CharField(blank=True, max_length=255, null=True)),
                ('repre', models.CharField(blank=True, max_length=255, null=True)),
                ('mandante', models.CharField(blank=True, max_length=255, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=255, null=True)),
                ('encargo', models.CharField(blank=True, max_length=255, null=True)),
                ('soli', models.CharField(blank=True, max_length=255, null=True)),
                ('arancel', models.IntegerField(blank=True, null=True)),
                ('estadoNoti', models.IntegerField(blank=True, null=True)),
                ('estadoCausa', models.IntegerField(blank=True, null=True)),
                ('actu', models.CharField(blank=True, max_length=255, null=True)),
                ('arancel_nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('nombreusuario', models.CharField(max_length=255)),
                ('apellidousuario', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
