# Generated by Django 5.1.3 on 2024-11-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Causa1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUD_notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNotificacion', models.DateTimeField()),
                ('numjui', models.CharField(max_length=255)),
                ('nombTribunal', models.CharField(max_length=255)),
                ('demandante', models.CharField(max_length=255)),
                ('demandado', models.CharField(max_length=255)),
                ('repre', models.CharField(max_length=255)),
                ('mandante', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('encargo', models.CharField(max_length=255)),
                ('soli', models.CharField(max_length=255)),
                ('arancel', models.IntegerField()),
                ('estadoNoti', models.IntegerField()),
                ('estadoCausa', models.IntegerField()),
                ('actu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'AUD_notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numjui', models.CharField(max_length=255)),
                ('nombTribunal', models.CharField(max_length=255)),
                ('demandante', models.CharField(max_length=255)),
                ('demandado', models.CharField(max_length=255)),
                ('repre', models.CharField(max_length=255)),
                ('mandante', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('encargo', models.CharField(max_length=255)),
                ('soli', models.CharField(max_length=255)),
                ('arancel', models.IntegerField()),
                ('actu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'demanda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNotificacion', models.DateField()),
                ('numjui', models.CharField(max_length=50)),
                ('nomb_tribunal', models.CharField(max_length=100)),
                ('demandante', models.CharField(max_length=100)),
                ('demandado', models.CharField(max_length=100)),
                ('repre', models.CharField(max_length=100)),
                ('mandante', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=100)),
                ('encargo', models.CharField(max_length=100)),
                ('soli', models.TextField()),
                ('arancel', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'demanda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('nombreusuario', models.CharField(max_length=255)),
                ('apellidousuario', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'managed': False},
        ),
    ]
